[project]
name = "case-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.5.3",
    "flower>=2.0.1",
    "gevent>=25.5.1",
    "numpy>=2.3.2",
    "pythonnet>=3.0.5",
    "redis>=5.2.1",
]
